# Generated by Django 3.1.1 on 2023-08-12 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prénom', models.CharField(max_length=50)),
                ('nom', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('numéro', models.CharField(max_length=15)),
                ('addresse', models.CharField(max_length=100)),
            ],
        ),
    ]
